export const SET_IS_BLURRED = '@@app/SET_IS_BLURRED'
export const SET_ACTIVE_PAGE = '@@app/SET_ACTIVE_PAGE'
export const SET_IS_NAV_OPEN = '@@app/SET_IS_NAV_OPEN'
export const DISABLE_INITIAL_ANIMATION = '@@app/DISABLE_INITIAL_ANIMATION'
